# Generated by Django 4.2.2 on 2023-06-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webclass', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=10)),
                ('message', models.TextField(max_length=255)),
            ],
        ),
    ]
