# Generated by Django 3.2.7 on 2023-08-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webclass', '0004_signin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=10)),
                ('subject', models.TextField(max_length=255)),
            ],
        ),
    ]
